### ISSUE TITLE
Bug in find_merge_commits.sh in the run_cf branch

### ISSUE THREAD

**Issue by benedikt-schesch** [benedikt-schesch/AST-Merging-Evaluation#22]
The following problem is printed when running ./src/scripts/find_merge_commits.sh cf/local_repos_cf.csv cf/merges_cf:
```
./src/scripts/find_merge_commits.sh: line 153: [[: 1
1: syntax error in expression (error token is "1")
./src/scripts/find_merge_commits.sh: line 153: [[: 1
1
1: syntax error in expression (error token is "1
1")
./src/scripts/find_merge_commits.sh: line 153: [[: 1
1: syntax error in expression (error token is "1")
```

**Comment by mernst** [comment]
Apparently fixed by 1d9e26384de3704dd21e04f55a984ece9f6ea8ec.

**Comment by benedikt-schesch** [comment]
Still present:
./src/scripts/find_merge_commits.sh: line 153: [: 1
1
2: integer expression expected
./src/scripts/find_merge_commits.sh: line 153: [: 1
1: integer expression expected
./src/scripts/find_merge_commits.sh: line 153: [: 1
1
1: integer expression expected
./src/scripts/find_merge_commits.sh: line 153: [: 2
1: integer expression expected
./src/scripts/find_merge_commits.sh: line 153: [: 1
1
1: integer expression expected

**Comment by mernst** [comment]
Please see https://github.com/benedikt-schesch/AST-Merging-Evaluation/issues/39 .
